services:
  db:
    image: postgis/postgis:18-3.6-alpine
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  storage:
    image: adobe/s3mock
    ports:
      - 9090:9090
      - 9191:9191
    environment:
      # - initialBuckets=places
      - COM_ADOBE_TESTING_S3MOCK_STORE_RETAIN_FILES_ON_EXIT=true
      - COM_ADOBE_TESTING_S3MOCK_STORE_ROOT=/var/s3mock
    volumes:
      - storage-data:/var/s3mock

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - 127.0.0.1:5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
  storage-data: