export enum PlaceType {
	LANDMARK = 'LANDMARK',
	RESTAURANT = 'RESTAURANT',
	CAFE = 'CAFE',
	BEACH = 'BEACH',
	BAR = 'BAR',
	MOVIE_THEATER = 'MOVIE_THEATER',
	NATURE = 'NATURE',
	MUSEUM = 'MUSEUM',
	CONCERT = 'CONCERT',
	HOTEL = 'HOTEL',
	MOTEL = 'MOTEL',
	HOSTEL = 'HOSTEL',
}
